exports.lines = [
'--------------------------------------------------------------------------------',
'-- This is a simple web server built using monoglot',
'--------------------------------------------------------------------------------',
'',
'local HTTPD = require "httpd"',
'local Dino = require "dino"',
'local thread = require "thread"',
'local opairs = require "opairs"',
'local doctree = require "doctree"',
'local trapFilter = require "trapfilter"',
'',
'local E = doctree.E',
'',
'',
'local defaultCSS = [[',
'body { font: 14px Arial; }',
'pre { background-color: #eee; color: black; border: 1px solid #888;',
'   padding: 2px; font: 12px Courier, monospace; }',
']]',
'',
'local style = E.style { defaultCSS }',
'',
'local welcome = {',
'   E.head {',
'      E.title { "Welcome" },',
'      style',
'   },',
'   E.h1 { "Home" },',
'   E.h2 { "Link" },',
'   E.p { E.a { href = "/show", "Show request details" } },',
'   E.h2 { "GET form" },',
'   E.p {',
'      E.form {',
'         method = "GET",',
'         action = "/show",',
'--[[',
'         E.input { type = "text", name = "a", },',
'         E.input { type = "submit", name = "b", value = "submit" },',
'--]]',
'      }',
'   },',
'}',
'',
'local function main()',
'   local port = os.getenv("port") or "127.0.0.1:" .. 8888',
'   server = HTTPD:new(port)',
'   server:start(trapFilter.wrap(dino))',
'   print("Listening on " .. port .. " ...")',
'end',
'',
'thread.dispatch(main)',
''];

exports.text = exports.lines.join('\n');
